### ISSUE TITLE
Recent commit complains

### ISSUE THREAD

**Issue by nitrogenez** [Hacknique/modular_computers#1]
Hi James.
It's nitro again.

It's a common practice to notify the repo members about massive changes in the project structure.
That's because then these massive changes are ok and they're manageable. However, you've made a commit a few minutes ago that made the project to a mod, not modpack, even though I have made my changes for a modpack, and now I'm at first unable to push my changes and should review diffs, and second I now need to restructure my local repo so it will fit the new structure on the remote.

Please, take your cooperators to consideration when you're making breaking changes.
If you don't want to, then either work alone or just start a new branch for your breaking changes, so we have time to prepare everything for transition.

**Comment by JamesClarke7283** [comment]
> Hi James. It's nitro again.
> 
> It's a common practice to notify the repo members about massive changes in the project structure. That's because then these massive changes are ok and they're manageable. However, you've made a commit a few minutes ago that made the project to a mod, not modpack, even though I have made my changes for a modpack, and now I'm at first unable to push my changes and should review diffs, and second I now need to restructure my local repo so it will fit the new structure on the remote.
> 
> Please, take your cooperators to consideration when you're making breaking changes. If you don't want to, then either work alone or just start a new branch for your breaking changes, so we have time to prepare everything for transition.

Okay, sorry, its noted.
