### ISSUE TITLE
[TODO] Create GitHub workflow for linting the code

### ISSUE THREAD

**Issue by nitrogenez** [Hacknique/modular_computers#10]
I consider that this issue is not up to debate, so marking it as a TODO.

It's a good and common practice to use automatic linting to ensure code quality and readability.

I assign myself on that issue.

**Comment by nitrogenez** [comment]
Okay, didn't see that this is already a thing in MOCO. Closing that issue as completed :)

**Comment by y5nw** [comment]
IMO it would also make sense to add unittests using [mineunit](https://github.com/S-S-X/mineunit). Not sure whether this is still on topic here tough.
