### ISSUE TITLE
[Proposition] Namespace organisation

### ISSUE THREAD

**Issue by nitrogenez** [Hacknique/modular_computers#4]
For the sake of readability and organisation I propose to move `registered_commands` to a separate namespace.

`ctr` is a global mod namespace. So it's a bit inconvinient to have a `command-callback` list in the root of that namespace.

My proposition is to move `ctr.registered_commands` into a sub-namespace. Like so: `ctr.NSP.registered_commands`, where NSP may be `storage`, `game`, or `int` (for `internal`).

The issue was raised to discuss the change and so other contributors don't freak out when they see their favourite command register is non-existent.

**Comment by y5nw** [comment]
> My proposition is to move `ctr.registered_commands` into a sub-namespace. Like so: `ctr.NSP.registered_commands`, where NSP may be `storage`, `game`, or `int` (for `internal`).

It would make sense as commands are apparently only for the OS level (for which a `os` namespace would make sense)

**Comment by nitrogenez** [comment]
> It would make sense as commands are apparently only for the OS level (for which a `os` namespace would make sense)

Right. That's why this issue is open. We need a confirmation from the maintainer to go any further. If we make changes without the maintainer's notice it'll be a lot of confusion.

**Comment by JamesClarke7283** [comment]
> For the sake of readability and organisation I propose to move `registered_commands` to a separate namespace.
> 
> `ctr` is a global mod namespace. So it's a bit inconvinient to have a `command-callback` list in the root of that namespace.
> 
> My proposition is to move `ctr.registered_commands` into a sub-namespace. Like so: `ctr.NSP.registered_commands`, where NSP may be `storage`, `game`, or `int` (for `internal`).
> 
> The issue was raised to discuss the change and so other contributors don't freak out when they see their favourite command register is non-existent.

I think this is a fair proposal. I already aimed to do this in future, but looking at it now, it might be important to address it now.
Although i think "int" could also mean "interrupt", "interface" or other things, so i would prefer "internal".

**I propose a function namespace of:**
```lua
modular_computers.internal.command.register([name], [callback])
```
**for users inside the terminal this API would be**
```lua
internal.command.register([name], [callback])
```

_Please note, i aim to make commands be auto registered when a lua script is in a directory that's specified in the `PATH` environment variable, like on GNU/Linux._

Let me know if you are happy with this.

**Comment by nitrogenez** [comment]
> > For the sake of readability and organisation I propose to move `registered_commands` to a separate namespace.
> > 
> > `ctr` is a global mod namespace. So it's a bit inconvinient to have a `command-callback` list in the root of that namespace.
> > 
> > My proposition is to move `ctr.registered_commands` into a sub-namespace. Like so: `ctr.NSP.registered_commands`, where NSP may be `storage`, `game`, or `int` (for `internal`).
> > 
> > The issue was raised to discuss the change and so other contributors don't freak out when they see their favourite command register is non-existent.
> 
> I think this is a fair proposal. I already aimed to do this in future, but looking at it now, it might be important to address it now.
> Although i think "int" could also mean "interrupt", "interface" or other things, so i would prefer "internal".
> 
> **I propose a function namespace of:**
> ```lua
> modular_computers.internal.command.register([name], [callback])
> ```
> **for users inside the terminal this API would be**
> ```lua
> internal.command.register([name], [callback])
> ```
> 
> _Please note, i aim to make commands be auto registered when a lua script is in a directory that's specified in the `PATH` environment variable, like on GNU/Linux._
> 
> Let me know if you are happy with this.

I personally am kind of happy with that solution. That's a nice approach.
