### ISSUE TITLE
[Qn] Licensing

### ISSUE THREAD

**Issue by nitrogenez** [Hacknique/modular_computers#8]
Currently MOCO is licensed under GNU AGPLv3.0. It's not a big deal, but AGPL is more oftenly used in web-related technologies, as it is suitable for that.

What if we relicense the project under GNU GPL, GNU LGPL, BSD-3-Clause? These might be a better choice.

I am a BSD guy, so I "vote" for BSD-3-Clause (a.k.a FreeBSD license).

**Comment by y5nw** [comment]
> Currently MOCO is licensed under GNU AGPLv3.0. It's not a big deal, but AGPL is more oftenly used in web-related technologies, as it is suitable for that.

It depends on what MOCO is intended for. If it is intended to use the mod on servers then AGPL could also make sense here as it would be web-related as well (see section 13 of the AGPL).

**Comment by JamesClarke7283** [comment]
> Currently MOCO is licensed under GNU AGPLv3.0. It's not a big deal, but AGPL is more oftenly used in web-related technologies, as it is suitable for that.
> 
> What if we relicense the project under GNU GPL, GNU LGPL, BSD-3-Clause? These might be a better choice.
> 
> I am a BSD guy, so I "vote" for BSD-3-Clause (a.k.a FreeBSD license).

The rationale behind selecting the AGPLv3.0 license for MOCO primarily revolves around fostering an environment of openness and collaborative enhancement, particularly in server-based deployments. AGPL's stipulation that mandates sharing source code alterations even in networked settings resonates with the objective of ensuring transparency and promoting collective contributions to the mod.

The proposition of transitioning to GPL or LGPL doesn't align with these goals in the context of networked deployments, as pointed out by @y5nw. Unlike AGPL, GPL doesn't extend the requirement of disclosing source code modifications to scenarios where the mod is utilized over a network, potentially creating a loophole that undermines the ethos of communal sharing and improvement we aim to uphold.

Similarly, LGPL's more permissive stance towards linking proprietary mods could inadvertently endorse a shift towards closed-source derivations, which is contrary to the mod's founding principles. Additionally, LGPL lacks the robust safeguard embodied in Section 13 of AGPL that @y5nw highlighted, which is crucial for preserving the mod's open-source nature in networked scenarios.

As for the BSD-3-Clause license, while it's revered for its permissiveness, it fundamentally diverges from our copyleft stance. It permits proprietary adaptations and redistributions without necessitating the sharing of altered source code, thus creating a pathway for privatization of communal efforts. This potential transition towards proprietary derivatives could stifle the culture of shared innovation and communal betterment that we aspire to nurture through MOCO.

In essence, the AGPLv3.0 license acts as a bulwark against the enclosure of software commons, ensuring that MOCO remains a collaborative endeavor with a shared objective of continual improvement and open accessibility. Hence, deviating from this license could potentially dilute the mod's core values and its commitment towards fostering a copyleft ecosystem.

**Comment by nitrogenez** [comment]
I see. Thank you for your reply. I guess it's really a cultural issue. As I thought. I'll mark this issue closed, as no further discussion is longer needed. :)
